### ISSUE TITLE
add pyqt=5 to installation step

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bs_model_instrument#6]
This step https://github.com/BCDA-APS/bs_model_instrument/blob/dda801d56acf454cc55b6bb96efdee4b4448eec4/README.md?plain=1#L16

also needs to install `pyqt=5` to get its Qt library dependencies installed.

**Comment by prjemian** [comment]
- https://github.com/prjemian/model_instrument/pull/5

**Comment by prjemian** [comment]
@MDecarabas - You reversed this in 7a7d5f0a71c089d478499987ad3cfeeb15fd58fb.  Why?

**Comment by MDecarabas** [comment]
When installing the package when specifying the binaries from Conda the package does not build properly and errors out. Creating a clean Conda environment with only the Pyepics binaries fixed that.

**Comment by prjemian** [comment]
Worked for me the way it is now.
